# Generated by Django 5.1.2 on 2024-10-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_prisoner_approved_approval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
    ]
