# Generated by Django 5.1.2 on 2024-10-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_approval_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='next_available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='previous_available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date_of_request', models.DateTimeField(auto_now_add=True)),
                ('desired_date', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('image_confirmation', models.ImageField(blank=True, null=True, upload_to='request_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.activitytype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='scheduler.prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_processes', to='scheduler.requesttemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
